#config.yaml

#absolute or relative
bamPath: /PATH_TO_YOUR_OWN_BAM_REPOSITORY/
cramPath: /PATH_TO_YOUR_OWN_CRAM_REPOSITORY/
outPath: /DIRECTORY_FOR_RESULTS/
HERVK_eref: resources/hervk_eref.tab
refHg19: /PATH_TO_WHERE_YOU_DOWNLOADED_REFERENCE_GENOME/hg19.fa
pythonScripts: pythonScripts
RepeatMaskerPath: /PATH_OF_REPEATMASKER_INSTALLATION/RepeatMasker/
genomeBuildGR: GRCh37
genomeBuildHg: hg19
element: LTR5_Hs
