#config.yaml

#absolute or relative
bamPath: /home/projectmine-mkooyman/retroseq/RetroSnakeSurfSara/bam/
cramPath: /home/maartenk/temp/RetroSnakeSurfSara/
outPath: results/
HERVK_eref: resources/hervk_eref.tab
refHg19: /cvmfs/softdrive.nl/projectmine_sw/resources/Build37/hg19/ucsc.hg19.fasta
pythonScripts: pythonScripts
genomeBuildGR: GRCh37
genomeBuildHg: hg37
element: LTR5_Hs
