#config.yaml

#absolute or relative
bamPath: /home/projectmine-mkooyman/retroseq/RetroSnakeSurfSara/bam/
cramPath: /home/projectmine-mkooyman/realignment/
outPath: results/
HERVK_eref: resources/hervk_eref.tab
refHg19: /home/projectmine-mkooyman/realignment/ref/hs38DH.fa
pythonScripts: pythonScripts
RepeatMaskerPath: /home/projectmine-mkooyman/miniconda3/envs/repeatmasker/share/RepeatMasker/
genomeBuildGR: GRCh38
genomeBuildHg: hg38
element: LTR5_Hs
