#config.yaml

#absolute or relative
cramPath: /home/projectmine-mkooyman/STEAK/
outPath: results/
HERVK_eref: resources/hervk_eref.tab
refHg19: hg38_retroseq/hg38.fa
pythonScripts: pythonScripts
genomeBuildGR: GRCh38
genomeBuildHg: hg38
element: LTR5_Hs
containerized_path: retroseq.sif
