#config.yaml

#absolute or relative
cramPath: /path2cram
outPath: results/
HERVK_eref: resources/hervk_eref.tab
refHg19: /cvmfs/softdrive.nl/kooyman/RetroSnake/hg38.fa.gz
pythonScripts: pythonScripts
genomeBuildGR: GRCh38
genomeBuildHg: hg38
element: LTR5_Hs
containerized_path: ../retroseq.sif
knownNR: resources/list_of_known_integration_sitesNRHg38.bed
sample: sample
